name: CI

on:
  pull_request:
    branches: "main"
    paths:
      - "**.rs"
      - "**.toml"
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  validate-pull:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
          - 1.61.0 # MSRV
    steps:
    - uses: actions/checkout@v3
    - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }} && rustup component add clippy --toolchain ${{matrix.toolchain}}
    # Validating the formatting of the project shouldn't do very much currently,
    # due to the `rustfmt`'s macro formatting options being nightly exlusive,
    # but hopefully shouldn't add any significant overhead in jobs, and require minimal maintainance in future...
    #
    # Additionally, the library is designed on the stable branch, meaning the check should run on a stable version.
    - name: Validate Formatting
      if: matrix.toolchain == 'stable'
      run: cargo fmt --check --verbose
    - name: Validate Clippy
      run: cargo clippy -- -D warnings --verbose
    - name: Validate Standard Tests
      run: cargo test --verbose
    # As this file is running tests on a library for generating tests,
    # it's required that it run tests on both standard tests,
    # and ignored cases, as generating such tests, is included in it's expected bahaviour...
    - name: Validate Ignored Tests
      run: cargo test --verbose -- --ignored

