name: Label PR

on:
  pull_request:
    branches: "main"
    types:
      - opened
  workflow_call:

jobs:
  label-pull:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    strategy:
      matrix:
        label:
          - adds tests
          - modifies tests
    steps:
      - name: ${{ matrix.label }}
        if: startsWith(github.event.pull_request.title, format("[{0}]", matrix.label))
        uses: andymckay/labeler@1.0.4
        with:
          add-labels: ${{ matrix.label }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          ignore-if-labeled: true
