name: Src CI

on:
  pull_request:
    branches: "main"
    paths:
      - "**.rs"
      - "**.toml"
      - "!Cargo.toml"
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  # Validating the formatting of the project shouldn't do anything currently,
  # due to the `rustfmt`'s macro formatting options being nightly exlusive,
  # but hopefully shouldn't add any significant overhead in jobs, and require minimal maintainance in future...
  #
  # Additionally, the library is designed on the stable branch, meaning the check should run on a stable version.
  validate-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate Formatting
        run: cargo fmt --check --verbose
  validate-build:
    needs: validate-fmt
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchains:
          - stable
          - beta
          - nightly
          - 1.6.3 # MSRV
    steps:
    - uses: actions/checkout@v3
    - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - name: Validate Clippy
      run: cargo clippy -- -D warnings --verbose
    - name: Validate Tests
      run: cargo test --verbose
        
